import styles from "./index.module.css";
import Head from "next/head";
import { useValidation, Validation } from "../lib";
import { z } from "zod";

const reg = /%|#|\$|@|!/;

const zType = z.string().email("This must be an email");
const vals = zType.parse("magerx1794@gmail.com");

const validation = Validation.createValidationSlice({
  firstName: Validation.new("")
    .length(2, 20)
    .match(/^[A-z]*$/)
    .blocking(),
  lastName: Validation.new("")
    .length(2, 20)
    .match(/^[A-z]*$/)
    .blocking(),
  username: Validation.new("").length(5, 10).not(),
  displayName: Validation.new("").length(2, 200).includes("@").blocking(),
  password: Validation.new("").match(reg),
  confirmPassword: Validation.new("").custom((val) => val.length > 5),
  email: Validation.new("").length(2, 200).includes("@"),
  button: Validation.new(""),
  //email: Validation.new("").parse(z.string().email("This must be an email")),
});

export default function Home() {
  const { sync, isValid, actions } = useValidation(validation);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        Username:{" "}
        <input
          {...sync(
            "username",
            {
              border: "thick double rgba(0,0,0,0)",
            },
            {
              border: "thick double red",
            }
          )}
          type={"text"}
          placeholder={"Enter your name"}
        />
        <input
          {...sync(
            "button",
            {
              border: "thick double rgba(0,0,0,0)",
            },
            {
              border: "thick double red",
            }
          )}
          placeholder={"Enter your name"}
          type="radio"
          checked={actions.watch("button") === "1"}
        />
      </main>
    </>
  );
}