import styles from "./index.module.css";
import Head from "next/head";
import { useValidation, Validation } from "react-validation-strategy";
import { z } from "zod";

const reg = /%|#|\$|@|!/;

const zType = z.string().email("This must be an email");
const vals = zType.parse("magerx1794@gmail.com");

const AccountValidation = Validation.createValidationSlice({
  firstName: Validation.new("")
    .length(2, 20)
    .match(/^[A-z]*$/)
    .blocking(),
  lastName: Validation.new("")
    .length(2, 20)
    .match(/^[A-z]*$/)
    .blocking(),
  username: Validation.new("").length(5, 10).not(),
  displayName: Validation.new("").length(2, 200).includes("@").blocking(),
  password: Validation.new("").match(reg),
  confirmPassword: Validation.new("").custom((val) => val.length > 5),
  email: Validation.new("").length(2, 200).includes("@"),
  //email: Validation.new("").parse(z.string().email("This must be an email")),
});

export default function Home() {
  const [syncInput, isValid] = useValidation(AccountValidation);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        Username:{" "}
        <input
          {...syncInput(
            "username",
            {
              border: "thick double rgba(0,0,0,0)",
            },
            {
              border: "thick double red",
            }
          )}
          type={"text"}
          placeholder={"Enter your name"}
        />
      </main>
    </>
  );
}

/*

First Name:{" "}
        <input
          style={{
            border: !isPropertyValid("firstName")
              ? "thick double red"
              : "thick double rgba(0,0,0,0)",
          }}
          value={getProperty("firstName")}
          type={"text"}
          placeholder={"Enter your name"}
          onChange={(event) =>
            updateProperties("firstName", event.currentTarget.value)
          }
        />
        Last Name:{" "}
        <input
          style={{
            border: !isPropertyValid("lastName")
              ? "thick double red"
              : "thick double rgba(0,0,0,0)",
          }}
          value={getProperty("lastName")}
          type={"text"}
          placeholder={"Enter your name"}
          onChange={(event) =>
            updateProperties("lastName", event.currentTarget.value)
          }
        />
        Username:{" "}
        <input
          style={{
            border: !isPropertyValid("username")
              ? "thick double red"
              : "thick double rgba(0,0,0,0)",
          }}
          value={getProperty("username")}
          type={"text"}
          placeholder={"Enter your name"}
          onChange={(event) =>
            updateProperties("username", event.currentTarget.value)
          }
        />
        Display:{" "}
        <input
          style={{
            border: !isPropertyValid("displayName")
              ? "thick double red"
              : "thick double rgba(0,0,0,0)",
          }}
          value={getProperty("displayName")}
          type={"text"}
          placeholder={"Enter your name"}
          onChange={(event) =>
            updateProperties("displayName", event.currentTarget.value)
          }
        />
        Password{" "}
        <input
          style={{
            border: !isPropertyValid("password")
              ? "thick double red"
              : "thick double rgba(0,0,0,0)",
          }}
          value={getProperty("password")}
          type={"password"}
          placeholder={"Enter your password"}
          onChange={eventChange((val) => updateProperties("password", val))}
        />
        Confirm Password{" "}
        <input
          style={{
            border: !isPropertyValid("confirmPassword")
              ? "thick double red"
              : "thick double rgba(0,0,0,0)",
          }}
          value={getProperty("confirmPassword")}
          type={"password"}
          placeholder={"Enter your password"}
          onChange={eventChange((val) =>
            updateProperties("confirmPassword", val)
          )}
        />
        Last Name:{" "}
        <input
         style={{
            border: false
              ? "thick double red"
              : "thick double rgba(0,0,0,0)",
          }}
          type={"text"}
          placeholder={"Enter your last name"}
        />

        */